<?php

/**
 * @file
 * Provides data feed functionality based on current timestamp.
 */

require_once dirname(__FILE__) . '/scheduled_feed.inc';

define('SCHEDULED_FEED_PERM_ADMIN', 'admin scheduled feed');


/**
 * Implements hook_views_api().
 */
function scheduled_feed_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_menu().
 */
function scheduled_feed_menu() {
  $items['admin/scheduledfeed/add'] = array(
    'title' => 'Scheduled Feed Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scheduled_feed_form_add'),
    'access arguments' => array('admin scheduled feed'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Returns a form for adding a new scheduled data
 */
function scheduled_feed_form_add() {
  $form['data'] = array(
    '#type' => 'textfield',
    '#title' => t('Data to be displayed'),
    '#default_value' => '',
    '#required' => TRUE,
  );
  $form['start'] = array(
    '#type' => 'textfield',
    '#title' => t('Start timestamp'),
    '#default_value' => '',
    '#required' => TRUE,
  );
  $form['end'] = array(
    '#type' => 'textfield',
    '#title' => t('End timestamp'),
    '#default_value' => '',
    '#required' => TRUE,
  );
  $form['is_default'] = array(
    '#type' => 'checkbox',
    '#title' => t('Set as default data returned?'),
    '#default_value' => FALSE,
  );
  $form['tid'] = array(
    '#type' => 'hidden',
    '#value' => SCHEDULED_FEED_PRIMARY_TID,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add data'),
  );

  return $form;
}

/**
 * Handles submitting new scheduled data
 */
function scheduled_feed_form_add_submit($form, &$form_state) {
  $data = (object) array(
    'data' => $form_state['values']['data'],
    'start' => $form_state['values']['start'],
    'end' => $form_state['values']['end'],
    'is_default' => $form_state['values']['is_default'],
    'tid' => $form_state['values']['tid'],
  );
  drupal_write_record('scheduled_feed_data', $data);
  dsm(t("New feed data was successfully saved."));
}





